import {
  Bootstrap,
  Express,
  JavaScript,
  Nodejs,
  Pug,
  React,
  ReactNative,
  Redux,
  SocketIO,
  SQL,
} from "../content/svg/";

export const projectsData = [
  {
    name: "IndiEats Customer App",
    summary:
      "A food delivery service for local independent restaurants. Android and iOS apps.",
    tech: [JavaScript, ReactNative, Redux, SocketIO],
    projectImages: [
      "https://i.imgur.com/6f0FhiN.png",
      "https://i.imgur.com/8GfMJ0P.png",
      "https://i.imgur.com/Ul8LdXR.png",
      "https://i.imgur.com/Be5ZCbU.png",
      "https://i.imgur.com/9SfJ5a1.png",
      "https://i.imgur.com/gaQXda0.png",
      "https://i.imgur.com/HZM23A5.png",
      "https://i.imgur.com/WV3NfCY.png",
      "https://i.imgur.com/pwV7Nq2.png",
      "https://i.imgur.com/j30YalB.png",
      "https://i.imgur.com/NZ5i6kh.png",
    ],
    imageShape: "phone",
    repoUrl: "",
    siteUrl: "",
  },
  {
    name: "Rees Work Time Log",
    summary: "A website for logging working hours and work order time.",
    tech: [JavaScript, React, Express, SQL],
    projectImages: [
      "https://i.imgur.com/pShGBBe.png",
      "https://i.imgur.com/jRBZaum.png",
      "https://i.imgur.com/g6BPScP.png",
      "https://i.imgur.com/8kodM8m.png",
      "https://i.imgur.com/89URvSO.png",
      "https://i.imgur.com/qVWTIWG.png",
    ],
    imageShape: "phone",
    repoUrl: "",
    siteUrl: "",
  },
  {
    name: "IndiEats Driver App",
    summary:
      "A delivery driver app for a local independent food delivery service. Android and iOS apps.",
    tech: [JavaScript, ReactNative, Redux, SocketIO],
    projectImages: [
      "https://i.imgur.com/0bGC51c.png",
      "https://i.imgur.com/lETIUiA.png",
      "https://i.imgur.com/9emvYFl.png",
      "https://i.imgur.com/afFccMb.png",
    ],
    imageShape: "phone",
    repoUrl: "",
    siteUrl: "",
  },
  {
    name: "IndiEats Landing Page",
    summary:
      "A landing page I made from a design mockup for a local independent food delivery service.",
    tech: [Nodejs, Express, Pug, Bootstrap],
    projectImages: [
      "https://i.imgur.com/Xtf8pTS.png",
      "https://i.imgur.com/0uMvqMQ.png",
      "https://i.imgur.com/jUrRd6A.png",
      "https://i.imgur.com/WulSVTc.png",
    ],
    repoUrl: "",
    siteUrl: "",
  },
  // {
  //   name: "Whisky Warehouse",
  //   summary:
  //     "A fake whisky store/catalogue in which you can create, edit, update and delete products.",
  //   tech: [Nodejs, Express, CSS, MongoDB],
  //   projectImages: ["https://i.imgur.com/pXsK5b3.jpg"],
  //   repoUrl: "https://github.com/ZakMcRae/inventory-application",
  //   siteUrl: "https://young-eyrie-64675.herokuapp.com/",
  // },
  // {
  //   name: "The Tool Store",
  //   summary: "Small E-Commerce page with functional shopping cart.",
  //   tech: [JavaScript, React, CSS, Git],
  //   projectImages: ["https://i.imgur.com/j5go8SC.jpg"],
  //   repoUrl: "https://github.com/ZakMcRae/shopping-cart",
  //   siteUrl: "https://zakmcrae.github.io/shopping-cart/",
  // },
  // {
  //   name: "The Blog",
  //   summary:
  //     "A blog website. Backend API learning project with basic Frontend MVC site.",
  //   tech: [Python, FastAPI, SQL, HTML, Bootstrap, SwaggerUI],
  //   projectImages: ["https://i.imgur.com/h95mM8l.jpg"],
  //   repoUrl: "https://github.com/ZakMcRae/psts-api",
  //   siteUrl: "https://api.psts.xyz/",
  // },
  // {
  //   name: "Simple Lists",
  //   summary: "A list website. Useful for keeping track of tasks and todos.",
  //   tech: [Python, Flask, HTML, Bootstrap, SQL, Nginx],
  //   projectImages: ["https://i.imgur.com/0pxD7ml.jpg"],
  //   repoUrl: "https://github.com/ZakMcRae/lsts",
  //   siteUrl: "https://lsts.xyz/",
  // },
];
